name: CI/CD - Backend

on:
  push:
    paths:
      - 'prueba-backend/**'
      - 'backend-ci.yml'
  pull_request:
    paths:
      - 'prueba-backend/**'

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build and test
        working-directory: prueba-backend
        run: mvn clean verify

      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: prueba-backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.50.1/trivy_0.50.1_Linux-64bit.tar.gz
          tar zxvf trivy_0.50.1_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Scan dependencies with Trivy
        run: trivy fs --scanners vuln --format template --template "@trivy-report.tpl" --severity HIGH,CRITICAL --output trivy_report.html .

      - name: Upload Trivy HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
            name: trivy-html-report
            path: trivy_report.html        


      - name: Build Docker Image
        run: docker build -t backend:latest prueba-backend

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: backend:latest
